# Generated by Django 3.0.5 on 2020-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('org', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
    ]
