# Generated by Django 3.0.5 on 2020-04-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
